/* Two selections from each array will be combined to create
campsite names */

module.exports.descriptors = [
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascading',
    'Silent',
    'Redwood',
    'Red', 
    'Blue',
    'Shady',
    'Breezy',
    'Misty',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
]

module.exports.places = [
    'Flats',
    'Village',
    'Town',
    'Hills',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Camp',
    'Forest',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Outpost',
]